---
- name: Test Domain Extractor Application
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      ignore_errors: true

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_version
      ignore_errors: true

    - name: Build and run Docker container
      docker_compose:
        project_src: .
        state: present
      when: docker_version.rc == 0 and docker_compose_version.rc == 0

    - name: Wait for application to start
      wait_for:
        port: 5000
        timeout: 30
      when: docker_version.rc == 0 and docker_compose_version.rc == 0

    - name: Test application health
      uri:
        url: http://localhost:5000
        return_content: yes
      register: app_health
      when: docker_version.rc == 0 and docker_compose_version.rc == 0

    - name: Stop and remove Docker container
      docker_compose:
        project_src: .
        state: absent
      when: docker_version.rc == 0 and docker_compose_version.rc == 0

    - name: Display test results
      debug:
        msg: "Application health check {{ 'passed' if app_health.status == 200 else 'failed' }}"
      when: docker_version.rc == 0 and docker_compose_version.rc == 0
